DROP TABLE IF EXISTS authors;
CREATE TABLE authors(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);
DROP TABLE IF EXISTS genre;
CREATE TABLE genres(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);
DROP TABLE IF EXISTS books;
CREATE TABLE books(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    author_id BIGINT,
    FOREIGN KEY (author_id) REFERENCES authors,
    genre_id BIGINT,
    FOREIGN KEY (genre_id) REFERENCES genres
);
CREATE INDEX idx_books_author_id ON books(author_id);
CREATE INDEX idx_books_genre_id ON books(genre_id);
DROP TABLE IF EXISTS comments;
CREATE TABLE comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1024),
    book_id BIGINT,
    FOREIGN KEY (book_id) REFERENCES books
);
CREATE INDEX idx_comments_book_id ON comments(book_id);